# mysql 연동
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/chimtooview?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=YoungTongCheif
#spring.datasource.username=root
spring.datasource.password=tmsp2zm

# sql 출력
spring.jpa.show-sql=false
# sql 이쁘게
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true

#server.ssl.key-store=keystore.p12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=tmsp2zm
#server.ssl.key-alias=bns-ssl